---
- name: Configurar e instalar agente SNMPD
  hosts: zabbixC
  port: 22
  vars:
    comunidade: hulk
    snmp_server: 172.25.250.254
  tasks:
  - yum: name=net-snmp state=latest 
  - template: src=./files/snmpd.conf.j2 dest=/etc/snmp/snmpd.conf owner=root group=root mode=0644 backup=yes
  - service: name=snmpd state=restarted enabled=yes
    when: ( ansible_distribution == "CentOS" or ansible_distribution == 'RedHat' ) and ansible_distribution_version < '7'
  - systemd: state=restarted daemon_reload=yes enabled=yes name=snmpd
    when: ( ansible_distribution == "CentOS" or ansible_distribution == 'RedHat' ) and ansible_distribution_version > '7'

